name: "Docs check"
# https://github.com/marketplace/actions/sphinx-build

on:
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
        # git is requried to clone the docs theme
        pre-build-command: "apt-get update -y && apt-get install -y git"
        docs-folder: "docs/"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
